### PR TITLE
Add angular2 templates

### PR DESCRIPTION
**Pull request by kentcooper**
Created 2 new Angular2 templates and a custom wizard to handle the class names. Also removed a couple of lines from TemplatePack/TemplatePackPackage.cs which were causing problems with DNX and VS2015. Should at least start to meet the request made in #337.

### CODE REVIEW

**Comment by johnpapa** [comment]
Thanks. This matches how I do it now in the VS Code templates and my style guide.

There will be updates. How do we want to be making those?

**Comment by kentcooper** [comment]
I didn't know you had a style guide for angular2! That's awesome. As for the updates..do you mean who will do the updates to sidewaffle?

**Comment by johnpapa** [comment]
It's not public yet ... very very early, but some things are forming well.

RE: updates ... i guess we'll just keep forking and PR-ing as needed.

**Comment by kentcooper** [comment]
Are there any more templates we need to add? I have just been playing with angular2 right now so I'm not sure what all is needed yet. Also we can line these up with your VS Code templates just to keep things consistent.

**Comment by johnpapa** [comment]
here they are

https://github.com/johnpapa/vscode-angular2-snippets/blob/master/snippets/typescript.json

**Comment by kentcooper** [comment]
Dang. I forgot about the pipes. Also you don't include the styles in the component? I was wondering if that should be in there or not. The few demo apps I've worked on I've used that property but mainly because it's in the tutorials. Not sure how much it will be used log term.

**Comment by kentcooper** [comment]
@johnpapa  okay I added the pipe template so we are inline with your VS templates, if you don't mind taking a look. If it looks okay to you I'll go ahead and merge.

**Comment by RandomlyKnighted** [comment]
I didn't have any issues when testing the templates.

@johnpapa does everything look good to you? If so I'll be happy to merge.

**Pull request merged**
