### PR TITLE
Added two new Angular 2 templates

### PR DESCRIPTION
**Pull request by MCKRUZ**
- bootstrap
- root component

Added 9 Typescript Snippets for when they get snippets working in typescript
- ng2-bootstrap
- ng2-component
- ng2-component-root
- ng2-http-get
- ng2-pipe
- ng2-route-path
- ng2-routes
- ng2-service
- ng2-subscribe

### CODE REVIEW

**Comment by sayedihashimi** [comment]
There is a build failure https://ci.appveyor.com/project/sayedihashimi/side-waffle. Is the build.ps1 file building successfully on your machine?

**Comment by MCKRUZ** [comment]
Yes.  And that wasn’t a file I altered at all.

**Comment by MCKRUZ** [comment]
it may have something to do with the project file changes...but I don't see why.

**Comment by MCKRUZ** [comment]
standby trying something

**Comment by MCKRUZ** [comment]
That seemed to fix it.

**Comment by RandomlyKnighted** [comment]
@madskristensen do you have anyone that could look over this PR as well as PR #385?

**Comment by madskristensen** [comment]
Looks good to me, if it wasn't for the merge conflicts

**Comment by RandomlyKnighted** [comment]
Awesome, I'll take a look at this tonight and see if I can't fix the merge conflict then I'll merge it in.

**Pull request merged**
