### PR TITLE
Added schema to templatesources.json

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This PR adds a schema to templatesources.json. This was done back in June but was never pull into the main repo.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Thanks, how is Schema set when the API constructs the file?

**Comment by RandomlyKnighted** [comment]
I don't think it is. That was one of the things that I was asking about a while back. The question I had originally was how do we validate against the schema programmatically? Is that even the correct way to do it?

**Comment by sayedihashimi** [comment]
I don't think we need to validate against it at runtime but when the file is created via API it would be helpful to have it. I think we can just set default value in the ctor.

**Comment by RandomlyKnighted** [comment]
I'm not sure I follow what you mean. The file is essentially recreated each time the settings window is saved.

**Comment by sayedihashimi** [comment]
When this code https://github.com/ligershark/side-waffle/blob/autoupdate/TemplatePack/Tooling/DynamicTemplateBuilder.cs#L270 executes the schema value will be null. I was suggesting to set the default value of Schema in the constructor.

**Comment by RandomlyKnighted** [comment]
Ah, I see what you mean now. I'll get started on that. Thanks for pointing it out.

**Comment by RandomlyKnighted** [comment]
I went ahead and assigned the schema in the runtime as well that way the ```templatesources.json``` is always correct.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I went ahead and made the change in Visual Studio Code. Any thing else I need to before we merge this PR?

**Comment by johnpapa** [comment]
What does this have to do with VS Code?

**Comment by RandomlyKnighted** [comment]
@johnpapa it doesn't. @sayedihashimi and I were talking earlier about making this change but I have been having an issue with Visual Studio. So I was just commenting that instead of waiting on it to reinstall I went ahead and opened the file in Visual Studio Code and fixed it.

**Comment by johnpapa** [comment]
ah. funny that you made a change in vs code for a vs thing. haha

**Comment by RandomlyKnighted** [comment]
haha I've had to do that surprisingly often lately. VS Code has been a lifesaver the past few days.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I just verified on my Surface that this works like expected. I enabled the Contoso templates and closed the settings window. When I looked at the ```templatesources.json`` it has the schema. 

Also I noticed that ```templatesources.json``` was located in ```%localappdata%\Microsoft\VisualStudio\14.0Exp\Extensions\LigerShark\SideWaffle Template Pack\1.17```. I thought it was supposed to appear in ```%localappdata%\LigerShark\SideWaffle\DynamicTemplates\1.2.0.0``` since it is likely to change in future versions?

**Comment by sayedihashimi** [comment]
Thanks merged it, I think the file should also get created under  %localappdata%\LigerShark\SideWaffle\DynamicTemplates\1.2.0.0 when enabled.

**Comment by RandomlyKnighted** [comment]
Alright, I'll fix that then will start working on merging master into autoupdate.

**Pull request merged**
