### PR TITLE
Fixed bugs found in recent PR

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This PR fixes the bug where some files were not able to be deleted due to an Access Denied error. The recursive parameter for the delete method has also been added to the second delete method call. The issue with the selected item of the ListView accidentally getting updated has also been fixed. 

The only bug remaining is with the menu item appearing 4 times instead of just once, which appears to be due to my editing of the VSCT file and the TemplatePackPackage.cs.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Sorry for the delay here, things have been kind of insane lately. Thanks a bunch for the changes, we are getting close to sharing this with some folks to get some feedback. I think for the most part we just have a few bugs to fix and then we can go ahead and do that. Here is what I have.

### Thoughts on next steps
 - Update icon in the menu to use SideWaffle.ico (or similar file) from /TemplatePack/resources
 - When installing templates we should consider showing a dialog stating that templates are being updated
 - We should see if we can install the templates in the background. I thinks @madskristensen is doing something similar in other extensions
 - Double check catch blocks to ensure that errors are being logged
 - Have we tested the update check to see if it works (_i.e. do you get daily update checks every day if selected?_)
 - Currently the template sources json file is stored under the extension folder. Is that what we want? The good thing is that if the user puts the file in a bad state he can uninstall/install the extension to get it restored back to original state. The bad thing is that when you uninstall/install all customizations are lost.
 - After Rebuild templates is invoked we should let the user know he may need to restart VS. Alternatively is there an API that we can call to get the templates refreshed? Sayed will investigate the API question.

**Comment by RandomlyKnighted** [comment]
When we check the catch blocks we should also look at the ProcessTemplates function and add logging for the UpdateLog.txt so that our LastWriteTime gets updated.

I have not tested the update check.

What if we stored a default sources.json file somewhere like GitHub and then added a button that copies the json file from wherever we're storing it to the user's computer. That way the user would not have to uninstall/reinstall the extension.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted I updated ProcessTemplates to touch the upgradelog file already so that should be there, unless you mean something else.

Regarding the storage of templateSources.json I opened issue #220 to track it. It is not needed for our initial release so let's focus on other items for now. We can circle back to that after we release this. In the next release we should include that feature. Users will have to reapply the settings for the second release but that's OK.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I was just going off of what Mads had said in his e-mail about how they do it in Web Essentials. 

"When Visual Studio starts up, it checks the LastWriteTime of the log file to figure out if 3 days have passed since last check. If 3 days have passed it sends a web request to look for new schema definitions. If none is found, then it writes that into the log file and thereby updates the LastWriteTime. If new schema definitions are available then it downloads them and writes the activity in the log file.  Either way, the log file gets updated and the LastWriteTime is updated."

When you updated ProcessTemplates you updated the LastWriteTime, but we aren't actually writing any activity to the log unless I've missed something.

**Comment by sayedihashimi** [comment]
Right I think that portion is right but its executing on the UI thread. I think @madskristensen has a way to do it in a background thread.

Regarding content since we are just looking at time stamp there is no need to populate that file. What I meant is we should log failures to vs activitylog

**Pull request merged**
