### PR TITLE
added angular 1.5 component template

### PR DESCRIPTION
**Pull request by ryanlangton**

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
@kentcooper Can you take a look at this please?

**Comment by RandomlyKnighted** [comment]
@johnpapa could you look this template over? It's been here for a while but has not been reviewed yet.

**Comment by RandomlyKnighted** [comment]
@madskristensen Can you look this PR over as well?

**Comment by johnpapa** [comment]
Would you be interested in making a Pr to the angular style guide for this?

**Comment by RandomlyKnighted** [comment]
@johnpapa was this good to merge?

**Pull request merged**
