### PR TITLE
nancy templates update as of 17/02/2016

### PR DESCRIPTION
**Pull request by nerobianchi**
1. packages are updated to latest version as of 17/02/2016
2. configs are updated
3. package versions of nancy are updated at razor related csproj files during post build
4. framework is set to 4.6.1

packages:

1. Nancy.1.4.3
2. Nancy.Hosting.Aspnet.1.4.1
3. Nancy.Hosting.Self.1.4.1
4. Nancy.Viewengines.Razor.1.4.3
5. Microsoft.AspNet.Razor.3.2.3

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
Thanks @nerobianchi. I'll take a look at this and see about merging them tonight.

**Comment by RandomlyKnighted** [comment]
@nerobianchi I had some issues getting the `Nancy empty project with ASP.NET host and Razor` template to work. Can you check it out and see if it is working for you?

Also can you update the release notes for version 1.21 to show that these templates have been updated?

**Comment by nerobianchi** [comment]
hi @RandomlyKnighted,

i created a new Nancy empty project with asp.net host and razor template and created appropriate contents on it.then there seems no error.i works.
could you please tell me what is the issue not to work?

is the comments above not sufficient for release note?

**Comment by RandomlyKnighted** [comment]
@nerobianchi I created a new project using that template to make sure that I didn't screw anything up the first time. When I run it I immediately get a 404 error. Naturally I assumed that was because there was no index.cshtml file as I had to add that in another one of the projects in order to get past the 404 error. However, this time after adding the index.cshtml file I still get a 404 error. Is there something else I need to do get the page to load with Nancy?

We put release notes in the `release-notes.xml` file. The website pulls this file from GitHub and parses the data. This way we always have the latest release notes on our website.

**Comment by nerobianchi** [comment]
@RandomlyKnighted A module which routes "/" has be added as well.
I also updated release notes.

**Comment by RandomlyKnighted** [comment]
@nerobianchi the only changes I see in your last commit was the update release notes. Can you push the commit with the new module as well?

**Comment by nerobianchi** [comment]
@RandomlyKnighted the module is added during testing the template. Because the template is Nancy empty project with ASP.NET host and Razor.

**Comment by kentcooper** [comment]
Checked on the templates and everything appears to be good. Going ahead and merging.

**Pull request merged**
