### PR TITLE
Commented out the telemetry for the SW-ProjectVSTemplateFile template

### LINKED ISSUE #350: Comment out telemetry in templates
I think we should put the `WizardExtension` in https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/_project.vstemplate.xml and https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/fsharp._project.vstemplate.xml in comments. Users who are creating templates outside of SideWaffle will not be able to run their templates because of this element. So we should uncomment when contributing to SideWaffle.

@RandomlyKnighted

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This fixes #350.

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
You'll have to ignore the commit message. I did a squash commit and messed it up somehow. All my commits were squashed successfully and all content in this PR is just like it should be. It just messed up the commit name.

**Comment by sayedihashimi** [comment]
Looks like there is a merge conflict here

**Comment by RandomlyKnighted** [comment]
@sayedihashimi That should fix it now.

**Comment by kentcooper** [comment]
@RandomlyKnighted any idea why all the appveyor builds are failing?

**Comment by kentcooper** [comment]
Never mind I just saw #356

**Comment by RandomlyKnighted** [comment]
@kentcooper Yep #356 is the cause of the problem. I'm working on a fix for it that I hope to have included in the next SideWaffle version.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi if you'll give me a few minutes I'll rebase this and make sure it passes in Appveyor.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi alright looks like we're good now.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi are we good to merge this?

**Pull request merged**
