### PR TITLE
Added Razor v3 web application

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
I know this is an old request but I've made a Razor v3 web application per #132.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Thanks for putting this together!
I see two RazorV3WebApplication folders, one in the root and one in Project Templates. Is that correct? It looks wrong.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi Yeah, not sure how that happened. I've just added a commit to fix that.

**Comment by sayedihashimi** [comment]
After registering a user I get an error when trying to login. I looked at it for a minute but haven't gotten to the bottom of it yet.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi  The issue you encountered with logging in should now be fixed. All I had to do was use the Package Manager Console to reinstall the packages for that project. Once I did that it finally started pulling in all the dependencies it needed to run correctly.

**Comment by sayedihashimi** [comment]
Here is a working project https://dl.dropboxusercontent.com/u/40134810/SideWaffle/pr-258/RazorV3WebApplication1.zip

Note: the .sdf file should be replaced with a blank one (_i.e. from a new project_)

I deleted packages.config and pretty much cleared out web.config besides the appSettings and maybe a few other things. Then I reinstalled all packages with in the package manager console

```powershell
Install-Package DotNetOpenAuth.AspNet -version 4.1.4.12333
Install-Package DotNetOpenAuth.Core -version 4.1.4.12333
Install-Package DotNetOpenAuth.OAuth.Consumer -version 4.1.4.12333
Install-Package DotNetOpenAuth.OAuth.Core -version 4.1.4.12333
Install-Package DotNetOpenAuth.OpenId.Core -version 4.1.4.12333
Install-Package DotNetOpenAuth.OpenId.RelyingParty -version 4.1.4.12333
Install-Package jQuery -version 1.10.2
Install-Package jQuery.UI.Combined -version 1.10.3
Install-Package jQuery.Validation -version 1.11.1
Install-Package knockoutjs -version 2.3.0
Install-Package Microsoft.AspNet.Razor -version 3.2.2
Install-Package Microsoft.AspNet.Web.Optimization -version 1.1.3
Install-Package Microsoft.AspNet.WebPages -version 3.2.2
Install-Package Microsoft.AspNet.WebPages.Data -version 3.2.2
Install-Package Microsoft.AspNet.WebPages.OAuth -version 3.2.2
Install-Package Microsoft.AspNet.WebPages.WebData -version 3.2.2
Install-Package Microsoft.jQuery.Unobtrusive.Validation -version 3.2.2
Install-Package Microsoft.SqlServer.Compact -version 4.0.8876.1
Install-Package Microsoft.Web.Infrastructure -version 1.0.0.0
Install-Package Modernizr -version 2.6.2
Install-Package WebGrease -version 1.5.2
```

Here is how I generated that script. Using a new Website Razor v3 I ran the following PowerShell commands.

```
[xml]$pkgs=Get-Content 'C:\Users\Sayed\Documents\Visual Studio 2013\WebSites\WebSite2\packages.config'
$pkgs.packages.package | % {'Install-Package {0} -version {1}' -f $_.id,$_.version}
```

@RandomlyKnighted I started working on adding this back to the project but then ran into some strange issues and ran out of time. Could you take it from here?

**Comment by RandomlyKnighted** [comment]
Sure, I've been at ballgames all afternoon, but we don't have another game until Thursday so give me a day or two and I should have it all worked out.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi  This actually went by quicker than I thought. I cleaned up everything in the packages.config file and then manually reinstalled everything like you suggested (via the Package Manager Console). I also went ahead and replaced the .sdf database file. 

After doing that I went ahead and rebuilt SideWaffle to test out the template. Unfortunately I ran into a problem where the Package Restore is not working correctly on my machine so I'm unable to test without manually reinstalling the packages via the Package Manager Console.If I commit my changes can you test what I've done?

**Comment by sayedihashimi** [comment]
Sure I can try it, likely tomorrow.

**Comment by RandomlyKnighted** [comment]
Ok, so I've tested this across 2 computers and so I'm still running into the same issue. There are a few references that I have been unable to get to install automatically when the new project is built. If I manually reinstall these packages then it loads fine. Am I setting up the project wrong in SideWaffle?

**Comment by sayedihashimi** [comment]
I looked at it. The reason you were getting the build error is due to the following in the project file.

```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
  </Target>
```

I think that was added when one of the NuGet packages was installed.

That is not the way that NuGet packages are restored anymore so it shouldn't even be trying to validate that, so I just removed it.

I also changed package hint paths to be ```..\packages``` instead of ```..\..\packages```. I think most projects in SideWaffle use ```..\packages```.

I also changed SortOrder so they display below existing SideWaffle templates.

Then I removed ```_bin_deployableAssemblies```, its only needed for publishing when Sql CE is used on the target machine.

I've merged it.

See commits
 - https://github.com/ligershark/side-waffle/commit/a016a6f9d064561b8910f4ab9a1ef1e193e5c312
 - https://github.com/ligershark/side-waffle/commit/f318928ea08bddaae69f5dae314ea4cc1e72a455

**Comment by RandomlyKnighted** [comment]
If NuGet packages aren't restored that way anymore then why would Visual Studio add it? I've got the latest update to Visual Studio.

**Comment by sayedihashimi** [comment]
It wasn't "Visual Studio" that added it, but instead one of the nuget packages.

**Pull request merged**
