### PR TITLE
Fixed invalid TemplateIds

### LINKED ISSUE #277: Updating invalid TemplateIds
There are ~10 files that contain invalid TemplateIds, i.e. ```$guid1$```. I briefly looked over the PowerShell script that added the TemplateIds and noticed that any Ids that were already existing were ignored. 

I think we should probably update the current script to so that instead of skipping a file that already contains a TemplateId it should verify that its value is valid.

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This fixes #277.

Once this is merged we will be ready to begin implementation of the the telemetry feature.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@RandomlyKnighted thanks for the PR.

There are two kinds of files template files here:
 1. Template files that are used by the SW Project Template Files item template 
 1. Template files that are installed into the users project when the SW Project Template Files item template is used

For the second set of files the value for TemplateID should be ```$guid1$``` so that when it is used a new ID is generated when it is used.

So the files under _Definitions should have a valid GUID, but for files like https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/_project.vstemplate.xml they should have ```$guid1$```.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi what about [this file](https://github.com/RandomlyKnighted/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/SideWaffle/SW-ProjectVSTemplateFile/fsharp._project.vstemplate.xml) should it used ```$guid1$``` as well?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted that file should have ```$guid1$``` and when the template is used when the file is dropped it should have a new unique guid.

**Comment by sayedihashimi** [comment]
Thanks @RandomlyKnighted,  I've merged it. I also updated the ```*.vstemplat-``` to use ```$guidN$``` in https://github.com/ligershark/side-waffle/commit/259bebbf858ed07da8d44062db758aefb8cce33b

**Comment by sayedihashimi** [comment]
Just merged to release, the build has started https://ci.appveyor.com/project/sayedihashimi/side-waffle/build/1.0.245

**Pull request merged**
