### PR TITLE
Update TypeScript AngularJS Controller Templates to work with Angular 1....

### PR DESCRIPTION
**Pull request by kentcooper**
Changed the controllers back to using class and constructor. Added static $inject field and and updated the function to set the controller. Also updated the mixed single and double quotes.

### CODE REVIEW

**Comment by kentcooper** [comment]
This should resolve the Issues reported in #111 and #182.

**Comment by kentcooper** [comment]
Not sure why it to 40 minutes for the build to run. Ran it locally and it completed without any errors.

**Comment by RobHudson72** [comment]
@kentcooper, thanks!  Glad you found a way to get classes to work.  I was flummoxed.

**Comment by kentcooper** [comment]
No problem glad I could help!

**Comment by sayedihashimi** [comment]
The build is going on for too long and timing out, does build.ps1 pass locally?

I'll investigate for my PC later.

**Comment by kentcooper** [comment]
Yep worked fine. Only took about a minute or so to run too.

**Comment by sayedihashimi** [comment]
It's not related to your changes, I'm investigating. Will merge soon.

**Comment by kentcooper** [comment]
Glad it wasn't anything I did.

**Comment by sayedihashimi** [comment]
The build is now passing, merged it. Can you send another pr with a new entry in release notes https://github.com/ligershark/side-waffle/blob/master/release-notes.html

**Comment by kentcooper** [comment]
I going to do that but this line "Updated Item Template - AngularJS templates updated to be Typescript 1.0 and Angular 1.3 compatible" kind of covered what I did. I can add something else if you want though.

**Comment by sayedihashimi** [comment]
Ok thanks no need then

**Pull request merged**
