### PR TITLE
Added SideWaffle logo to the Tools menu

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
I got one of my friends to edit the SideWaffle logo in Photoshop since it was hard to make out the 16x16 logo in Visual Studio. By changing the VS logo to blue we were able to get the image to look clearer in VS.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@RandomlyKnighted thanks for the PR. I've merged it, the icon looks nice man!

One thing that I noticed is that there is no way to remove a source. Could you add a Remove button? I think we can just put a Remove button next to New Source and enable it only when a row is selected in the grid.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi Awesome! One thing my friend and I noticed last night working on it was how much clearer the VS icons are at that small of a size. We'd love to chat with whoever made the Azure Websites glyphs to find out how they were able to make their icons look so clear at that small size.

Sure, I can do that. It'll probably be a couple days before I can get started though.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted if you have specific questions on the graphics you can email me and I'll add someone who can help with details. I think the icons are created from vector graphics but not sure.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi is there anything else besides a delete button that you need me to do before I create a pull request?

**Comment by sayedihashimi** [comment]
Lets go with what you have and I'll take a fresh look after that. I think that might be it. If so then we should share it with and folks and get some testing/feedback.

**Comment by RandomlyKnighted** [comment]
Are you going to send our a VSIX to those testing it or will the be testing it some other way?

**Comment by sayedihashimi** [comment]
Vsix is available at https://ci.appveyor.com/project/sayedihashimi/side-waffle/build/1.0.114/artifacts. Lets start testing. I will send out more details here in a day or so (on vacation).

**Comment by RandomlyKnighted** [comment]
Sounds good. Have a great vacation!!

**Comment by sayedihashimi** [comment]
Thanks, will do

**Pull request merged**
