### PR TITLE
Added the run settings item template.

### PR DESCRIPTION
**Pull request by RehanSaeed**
See https://github.com/ligershark/side-waffle/issues/335.

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
It looks like you're missing the elements for the telemetry in your vstemplate files. [Here's an example](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Extensibility/VS%20Command%20Table/_Definitions/CSharp.vstemplate#L76) of what it should look like. The value of ```$TemplateName$``` should be the same as what you have for the name element at the top of the file. ```$TemplateID$``` will have to be a newly generated GUID, and both the ```$TemplateType$``` along with the Wizard Extension elements can just be copied as is.

**Comment by RehanSaeed** [comment]
Added the telemetry config.

**Comment by RandomlyKnighted** [comment]
Alright, just tested this and found two issues. First, I was unable to get it to create the template at the solution level. It would only let me create it at the project level. Once I did that it would not let me move it to the solution level.

Second, can you added the new template to the release notes.

@sayedihashimi any suggestions on how we can set it up so that the template shows up when you open the Add New Item dialog from the solution level?

**Comment by sayedihashimi** [comment]
Try adding

```
<AppliesTo>ABC | (!ABC)</AppliesTo>
```

Example https://github.com/ligershark/side-waffle/blob/56a166f3c4089675f36b85a1bd0ff2825f36eead/TemplatePack/ItemTemplates/Misc/Dockerfile/_Definitions/Web.csharp.vstemplate#L11

**Comment by RehanSaeed** [comment]
Updated release notes and added the line @sayedihashimi suggested.

**Comment by RandomlyKnighted** [comment]
Awesome! I'm about to head to work but I'll test this out today.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I just tested this again and it still only shows up if you open the Add New Item dialog from the project level. If you right click on the solution and go to the Add New Item dialog the nodes available to choose from are shown in the image below.


sidewaffle_solution_level_bug

**Comment by sayedihashimi** [comment]
@scottaddie can you help here?

**Comment by scottaddie** [comment]
@sayedihashimi Both Svet and Phil were looking into this for me a few weeks back. In my situation, the item template was appearing in the New Item dialog for a Solution Folder, and I wanted to remove it from there. They asked that I experiment with the `AppliesTo` and `ShowByDefault` nodes. I hacked at that for several hours and had no luck.

It may be worth circling back with them or Viktor to see if they've had a chance to figure it out. I'd be very curious to hear what they've found, as I need to solve the problem for my item template as well.

**Comment by sayedihashimi** [comment]
@scottaddie I was the one who added you to the thread with Svet :) I was hoping you had more info after playing around with AppliesTo and ShowByDefault.

I'm not sure how to proceed, maybe we can ask on stackoverflow.com, maybe someone there knows?

**Comment by sayedihashimi** [comment]
@RehanSaeed @RandomlyKnighted OK I've looked at this. Here is what I found out.

In the `CSharp.vstemplate` file I added the following element ```<AppliesTo>!VB</AppliesTo>``` and to the `VB.vstemplate` file ```<AppliesTo>!CSharp</AppliesTo>```.

That by itself didn't make any difference.

Then I moved the `RunSettings` folder from `Test` to under `Web` and after that the result is:

runsettings

I'm not sure why moving the template under Web makes it show up in the Add Item dialog for solution folders. I am pretty confident that it's not a SideWaffle/TemplateBuilder issue, but instead a core VS issue. We may not get any traction in fixing that issue so we will have to make due with what we have.

@RehanSaeed how important is it to have the template under `Test` node for Add Item inside of projects? If it's important, and it's important to show in the Add Item dialog for solution items, then maybe we can add a template into `Test` that doesn't use `AppliesTo` and then we add the same content under `Web` and use `AppliesTo` to make it show there as well.

**Comment by RehanSaeed** [comment]
This template only really makes sense when added to a solution and makes no sense for a project.

Looks like the [RunSettings](https://visualstudiogallery.msdn.microsoft.com/1cc3863b-f15f-4107-bb05-3586fd65540b) extension adds uses the 'General' category.

untitled

**Comment by sayedihashimi** [comment]
@RehanSaeed I looked at that extension and here is the .vstemplate file it's using.

```
<VSTemplate Version="3.0.0" xmlns="http://schemas.microsoft.com/developer/vstemplate/2005" Type="Item">
  <TemplateData>
    <DefaultName>CompleteRunsettings.runsettings</DefaultName>
    <Name>CompleteRunsettings</Name>
    <Description>Default runsettings file with all elements, and parallel enabled.</Description>
    <ProjectType>General</ProjectType>
    <SortOrder>10</SortOrder>
    <Icon>star10.ico</Icon>
  </TemplateData>
  <TemplateContent>
    <References />
    <ProjectItem TargetFileName="$fileinputname$.runsettings" ReplaceParameters="false">AllRunSettings.runsettings</ProjectItem>
    
  </TemplateContent>
</VSTemplate>
```

You could probably do something similar here. Do you want to update the PR and let me know when to review/merge it?

**Comment by RehanSaeed** [comment]
The only difference I can see is that instead of CSharp, VB and Web ProjectType's, they only have General. I've made that change.

**Comment by RandomlyKnighted** [comment]
@RehanSaeed can you rebase this please?

**Comment by RehanSaeed** [comment]
Still not confident in doing a git rebase but I think I'm there. Appveyor is not happy though, I'm not sure why.

**Comment by sayedihashimi** [comment]
It looks like you have a file named "general.vstemplate" that should be changed to "csharp.general". It's probably a bug in TemplateBuilder but changing file name should fix it.

**Comment by RehanSaeed** [comment]
Done

**Pull request merged**
