### PR TITLE
Angularjs directive usage

### LINKED ISSUE #285: AngularJS directive template usage comment not displaying proper values
Not sure if we will be able to resolve it or not but in the directive template there is a usage example that when the $safeitemname$ is camel case the comment is not correct. For example when the directive name is directTest you end up with this:

      .directive('directiveTest', directiveTest);

        // Usage:
        //     <directiveTest></directiveTest>

when it should be:

       .directive('directiveTest', directiveTest);

        // Usage:
        //     <directive-test></directive-test>

Issue comes from https://visualstudiogallery.msdn.microsoft.com/a16c2d07-b2e1-4a25-87d9-194f04e7a698 QA section

### PR DESCRIPTION
**Pull request by kentcooper**
Fixed bug with the angularjs directive template by adding a custom wizard to properly format the usage comment. Also added the usage comment to the TypeScript AngularJs directive template. Should resolve #285

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
On the release notes you misspelled Angular

**Comment by kentcooper** [comment]
Ugg..that's what I get for typing at 2 am. Thanks for finding it.

**Comment by RandomlyKnighted** [comment]
No problem.

**Comment by kentcooper** [comment]
No other issues? Are we good to merge?

**Comment by RandomlyKnighted** [comment]
Not from me. If @johnpapa says things are ok then I'll be happy to merge them. I haven't got into Angular yet so I still don't know what I'm looking at haha

**Pull request merged**
