### PR TITLE
Merge dynamic templates into master

### PR DESCRIPTION
**Pull request by RandomlyKnighted**
This completes #226 and gets us ready for a new release.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
@RandomlyKnighted I think we are ready to merge this right?

**Comment by RandomlyKnighted** [comment]
You was having issues the other day with something. Was that with dynamic templates or something else? If it was something else then yes we are ready to merge.

**Comment by sayedihashimi** [comment]
@RandomlyKnighted no, I was having machine issues related to building. It's unrelated to the code here.

**Comment by RandomlyKnighted** [comment]
Alright, then we are ready to merge. 

If it's alright with you can we wait before doing a new release? I'm working on the website and I'd like to see if I can pull the template-report.xml file from GitHub. If I can't get it then we have to update SideWaffle so that it creates a HTML file with the same information. I'm going to test it this afternoon and will let you know.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I was able to pull the XML content from the last GitHub release. Feel free to merge and release whenever you're ready.

**Pull request merged**
