### PR TITLE
angularjs template for service

### PR DESCRIPTION
**Pull request by jfernandeze**
I've added prevent for jshint

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
cc: @kentcooper 

Kent can you look at this please?

**Comment by kentcooper** [comment]
@johnpapa if you get a second you mind checking this out since you did the original? I'm personally not a big fan of adding linter exclusions to a template though.

**Comment by johnpapa** [comment]
as long as the name of the function is UpperCase then this is not needed. So I'd skip this.

**Comment by kentcooper** [comment]
@jfernandeze thanks for the PR, but given @johnpapa's comments and my own feelings on not wanting linter comments in the templates I'm going to close this PR. If you see anything else in the templates that could use improvement or a template we may be missing please continue to contribute.

**Pull request closed without merging**
